swagger: "2.0"
produces:
  - application/json
consumes:
  - application/json
info:
  description: REST API for taking and managing bids for an auction
  title: Auction API
  version: 1.0.0
host: localhost:61125
basePath: /api/v1
schemes:
  - http

paths:
  /statistics/{item_number}:
    get:
      operationId: getBidStats
      tags:
        - Statistics
      parameters:
        - name: item_number
          in: path
          required: true
          type: integer
          minimum: 1
          description: Item number to get statistics for
      responses:
        200:
          description: OK get stats for item
          schema:
            type: object
            $ref: "#/definitions/Statistics"
        401:
          description: Endpoint currently disabled
          schema:
            type: object
            $ref: "#/definitions/ErrorResponse"
  /bids:
    get:
      operationId: getAllBids
      tags:
        - Bidding
      responses:
        200:
          description: OK get all bids
          schema:
            type: array
            items:
              $ref: "#/definitions/ItemSummary"
        401:
          description: Endpoint currently disabled
          schema:
            type: object
            $ref: "#/definitions/ErrorResponse"
  /bids/{item_number}:
    get:
      operationId: getAllBidsForItem
      tags:
        - Bidding
      parameters:
        - name: item_number
          in: path
          required: true
          type: integer
          minimum: 1
          description: Item number to bid on
      responses:
        200:
          description: OK get bids for this item
          schema:
            type: object
            $ref: "#/definitions/ItemSummary"
        401:
          description: Endpoint currently disabled
          schema:
            type: object
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: makeBid
      tags:
        - Bidding
      parameters:
        - name: item_number
          in: path
          required: true
          type: integer
          minimum: 1
          description: Item number to bid on
        - name: bid
          in: body
          schema:
            type: object
            $ref: "#/definitions/Bid"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Bid"
        400:
          description: Bad format
        403:
          description: Bid disallowed
        401:
          description: Endpoint currently disabled
          schema:
            type: object
            $ref: "#/definitions/ErrorResponse"

definitions:
  Statistics:
    type: object
    required:
      - no_of_bids
    properties:
      no_of_bids:
        x-nullable: false
        type: integer
        example: 3
  Bid:
    type: object
    required:
      - bid_amount
      - bidder_name
      - bidder_email
    properties:
      item_number:
        type: integer
        readOnly: true
        example: 15
      bid_amount:
        type: integer
        example: 20
      bidder_name:
        type: string
        example: John Doe
      bidder_email:
        type: string
        format: email
        example: johndoe@mail.com
  ItemSummary:
    type: array
    items:
      $ref: "#/definitions/Bid"
  ErrorResponse:
    type: object
    properties:
      error_message:
        type: string
