swagger: "2.0"
produces:
  - application/json
consumes:
  - application/json
info:
  description: REST API for taking and managing bids for an auction
  title: Auction API
  version: 1.0.0
basePath: /api/v1
schemes:
  - http

paths:
  /bids:
    get:
      operationId: getAllBids
      tags:
        - Bidding
      responses:
        200:
          description: OK get all bids
          schema:
            type: array
            items:
              $ref: "#/definitions/ItemSummary"
  /bids/{item_number}:
    get:
      operationId: getAllBidsForItem
      tags:
        - Bidding
      parameters:
        - name: item_number
          in: path
          required: true
          type: integer
          minimum: 1
          description: Item number to bid on
      responses:
        200:
          description: OK get bids for this item
          schema:
            type: object
            $ref: "#/definitions/ItemSummary"
    post:
      operationId: makeBid
      tags:
        - Bidding
      parameters:
        - name: item_number
          in: path
          required: true
          type: integer
          minimum: 1
          description: Item number to bid on
        - name: bid
          in: body
          schema:
            type: object
            $ref: "#/definitions/Bid"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Bid"
        400:
          description: Bad format
        403:
          description: Bid disallowed

definitions:
  Bid:
    type: object
    required:
      - item_number
      - bid_amount
      - bidder_name
      - bidder_email
    properties:
      item_number:
        type: integer
        example: 15
      bid_amount:
        type: integer
        example: 20
      bidder_name:
        type: string
        example: John Doe
      bidder_email:
        type: string
        format: email
        example: johndoe@mail.com
  ItemSummary:
    type: array
    items:
      $ref: "#/definitions/Bid"
